export const entities = {
  profile: {
    title: "Profile",
    subtitle: "Manage your personal portfolio profile",
    endpoint: "/profiles",
    columns: ["full_name", "profession", "email", "location", "availability_status"],
    fields: [
      { name: "full_name", label: "Full Name", type: "text", required: true, placeholder: "e.g. John Doe" },
      { name: "profession", label: "Profession", type: "text", placeholder: "e.g. Full Stack Developer" },
      { name: "headline", label: "Headline", type: "text", placeholder: "e.g. I build modern web experiences" },
      { name: "bio", label: "Bio", type: "textarea", placeholder: "Short bio for hero section..." },
      { name: "about", label: "About", type: "textarea", placeholder: "Detailed about section content..." },
      { name: "photo", label: "Profile Photo", type: "image", required: false },
      { name: "phone", label: "Phone", type: "text", placeholder: "e.g. +250 788 000 000" },
      { name: "email", label: "Email", type: "email", placeholder: "e.g. you@example.com" },
      { name: "location", label: "Location", type: "text", placeholder: "e.g. Kigali, Rwanda" },
      { name: "years_experience", label: "Years Experience", type: "number", placeholder: "e.g. 2" },
      { name: "projects_completed", label: "Projects Completed", type: "number", placeholder: "e.g. 20" },
      { name: "happy_clients", label: "Happy Clients", type: "number", placeholder: "e.g. 15" },
      { name: "technologies_count", label: "Technologies Count", type: "number", placeholder: "e.g. 10" },
      {
        name: "availability_status",
        label: "Availability",
        type: "select",
        options: ["Available", "Busy"],
        placeholder: "Select availability",
      },
    ],
  },
  skills: {
    title: "Skills",
    subtitle: "Manage your technical skills",
    endpoint: "/skills",
    columns: ["name", "category", "level", "percentage", "display_order"],
    fields: [
      { name: "name", label: "Skill Name", type: "text", required: true, placeholder: "e.g. React" },
      { name: "category", label: "Category", type: "text", placeholder: "e.g. Frontend" },
      { name: "icon", label: "Skill Icon", type: "icon", placeholder: "Upload skill icon (PNG, SVG)" },
      {
        name: "level",
        label: "Level",
        type: "select",
        options: ["Beginner", "Intermediate", "Advanced", "Expert"],
        placeholder: "Select skill level",
      },
      { name: "percentage", label: "Percentage", type: "number", placeholder: "e.g. 85" },
      { name: "display_order", label: "Display Order", type: "number", placeholder: "e.g. 1" },
    ],
  },
  projects: {
    title: "Projects",
    subtitle: "Manage portfolio projects",
    endpoint: "/projects",
    columns: ["title", "category", "status", "featured"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, placeholder: "e.g. E-commerce Platform" },
      { name: "slug", label: "Slug", type: "text", placeholder: "e.g. ecommerce-platform" },
      { name: "short_description", label: "Short Description", type: "textarea", placeholder: "Brief project summary..." },
      { name: "description", label: "Description", type: "textarea", placeholder: "Full project description..." },
      { name: "github_url", label: "GitHub URL", type: "text", placeholder: "https://github.com/username/repo" },
      { name: "live_demo", label: "Live Demo URL", type: "text", placeholder: "https://your-demo.com" },
      { name: "video_demo", label: "Video Demo", type: "video", placeholder: "Upload project demo video" },
      { name: "tech_stack", label: "Tech Stack", type: "textarea", placeholder: "React, Node.js, MySQL..." },
      { name: "category", label: "Category", type: "text", placeholder: "e.g. Web App" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Completed", "In Progress", "Archived"],
        placeholder: "Select status",
      },
      { name: "featured", label: "Featured", type: "checkbox" },
    ],
  },
  projectImages: {
    title: "Project Images",
    subtitle: "Manage project screenshots and images",
    endpoint: "/project-images",
    columns: ["project_id", "image_url", "caption", "display_order"],
    fields: [
      {
        name: "project_id",
        label: "Project",
        type: "select",
        required: true,
        optionsFrom: "/projects",
        optionLabel: "title",
        placeholder: "Select a project",
      },
      { name: "image_url", label: "Project Image", type: "image", required: true },
      { name: "caption", label: "Caption", type: "text", placeholder: "e.g. Dashboard screenshot" },
      { name: "display_order", label: "Display Order", type: "number", placeholder: "e.g. 1" },
    ],
  },
  experience: {
    title: "Experience",
    subtitle: "Manage work experience",
    endpoint: "/experiences",
    columns: ["company", "position", "location", "start_date", "current_job"],
    fields: [
      { name: "company", label: "Company", type: "text", required: true, placeholder: "e.g. Tech Company Ltd" },
      { name: "position", label: "Position", type: "text", required: true, placeholder: "e.g. Full Stack Developer" },
      { name: "employment_type", label: "Employment Type", type: "text", placeholder: "e.g. Full-time, Contract" },
      { name: "location", label: "Location", type: "text", placeholder: "e.g. Kigali, Rwanda" },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
      { name: "current_job", label: "Current Job", type: "checkbox" },
      { name: "description", label: "Description", type: "textarea", placeholder: "Describe your role and achievements..." },
      { name: "company_logo", label: "Company Logo", type: "image" },
    ],
  },
  education: {
    title: "Education",
    subtitle: "Manage education history",
    endpoint: "/education",
    columns: ["institution", "degree", "field", "start_year", "end_year"],
    fields: [
      { name: "institution", label: "Institution", type: "text", required: true, placeholder: "e.g. University of Rwanda" },
      { name: "degree", label: "Degree", type: "text", placeholder: "e.g. Bachelor of Science" },
      { name: "field", label: "Field", type: "text", placeholder: "e.g. Computer Science" },
      { name: "start_year", label: "Start Year", type: "number", placeholder: "e.g. 2018" },
      { name: "end_year", label: "End Year", type: "number", placeholder: "e.g. 2022" },
      { name: "description", label: "Description", type: "textarea", placeholder: "Additional details..." },
    ],
  },
  certifications: {
    title: "Certifications",
    subtitle: "Manage certifications and credentials",
    endpoint: "/certifications",
    columns: ["title", "issuer", "issue_date"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, placeholder: "e.g. AWS Certified Developer" },
      { name: "issuer", label: "Issuer", type: "text", placeholder: "e.g. Amazon Web Services" },
      { name: "issue_date", label: "Issue Date", type: "date" },
      { name: "credential_url", label: "Credential URL", type: "text", placeholder: "https://credential-url.com" },
      { name: "certificate_image", label: "Certificate Image", type: "image" },
    ],
  },
  blogCategories: {
    title: "Blog Categories",
    subtitle: "Organize blog posts by category",
    endpoint: "/blog-categories",
    columns: ["name", "slug"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "e.g. Web Development" },
      { name: "slug", label: "Slug", type: "text", placeholder: "e.g. web-development" },
    ],
  },
  blogs: {
    title: "Blogs",
    subtitle: "Manage blog posts",
    endpoint: "/blogs",
    columns: ["title", "category_id", "published", "views"],
    fields: [
      {
        name: "category_id",
        label: "Category",
        type: "select",
        optionsFrom: "/blog-categories",
        optionLabel: "name",
        placeholder: "Select category",
      },
      { name: "title", label: "Title", type: "text", required: true, placeholder: "e.g. Building Scalable APIs" },
      { name: "slug", label: "Slug", type: "text", placeholder: "e.g. building-scalable-apis" },
      { name: "excerpt", label: "Excerpt", type: "textarea", placeholder: "Short preview text..." },
      { name: "content", label: "Content", type: "textarea", placeholder: "Full blog post content..." },
      { name: "cover_image", label: "Cover Image", type: "image" },
      { name: "published", label: "Published", type: "checkbox" },
    ],
  },
  testimonials: {
    title: "Testimonials",
    subtitle: "Manage client testimonials",
    endpoint: "/testimonials",
    columns: ["client_name", "company", "rating", "featured"],
    fields: [
      { name: "client_name", label: "Client Name", type: "text", required: true, placeholder: "e.g. John Smith" },
      { name: "position", label: "Position", type: "text", placeholder: "e.g. CEO" },
      { name: "company", label: "Company", type: "text", placeholder: "e.g. Acme Corp" },
      { name: "photo", label: "Client Photo", type: "image" },
      { name: "message", label: "Message", type: "textarea", placeholder: "What the client said about your work..." },
      { name: "rating", label: "Rating (1-5)", type: "number", placeholder: "e.g. 5" },
      { name: "featured", label: "Featured", type: "checkbox" },
    ],
  },
  socialLinks: {
    title: "Social Links",
    subtitle: "Manage social media links",
    endpoint: "/social-links",
    columns: ["platform", "url", "display_order"],
    fields: [
      { name: "platform", label: "Platform", type: "text", required: true, placeholder: "e.g. GitHub" },
      { name: "url", label: "URL", type: "text", required: true, placeholder: "https://github.com/username" },
      { name: "icon", label: "Social Icon", type: "icon", placeholder: "Upload platform icon" },
      { name: "display_order", label: "Display Order", type: "number", placeholder: "e.g. 1" },
    ],
  },
  resume: {
    title: "Resume",
    subtitle: "Manage resume files",
    endpoint: "/resume",
    columns: ["title", "file_url", "version", "last_updated"],
    fields: [
      { name: "title", label: "Title", type: "text", placeholder: "e.g. Your Name - CV" },
      { name: "file_url", label: "Resume File", type: "file", required: true },
      { name: "version", label: "Version", type: "text", placeholder: "e.g. v2.0" },
      { name: "last_updated", label: "Last Updated", type: "date" },
    ],
  },
  settings: {
    title: "Site Settings",
    subtitle: "Configure global site settings",
    endpoint: "/site-settings",
    columns: ["site_name", "contact_email", "primary_color"],
    fields: [
      { name: "site_name", label: "Site Name", type: "text", placeholder: "e.g. Portek" },
      { name: "logo", label: "Logo", type: "image" },
      { name: "favicon", label: "Favicon", type: "image" },
      { name: "primary_color", label: "Primary Color", type: "text", placeholder: "e.g. #00d166" },
      { name: "secondary_color", label: "Secondary Color", type: "text", placeholder: "e.g. #0a0c10" },
      { name: "footer_text", label: "Footer Text", type: "text", placeholder: "e.g. Built with passion" },
      { name: "contact_email", label: "Contact Email", type: "email", placeholder: "e.g. contact@portek.dev" },
      { name: "contact_phone", label: "Contact Phone", type: "text", placeholder: "e.g. +250 788 000 000" },
      { name: "copyright", label: "Copyright", type: "text", placeholder: "e.g. © 2026 Portek" },
    ],
  },
};
